image: registry.gitlab.com/pages/quarto:latest 

pages:
  script:
    - quarto render 
    - mv docs public  # <-- 주목할 부분: docs 폴더 사용

  artifacts:
    paths:
      - public
      
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH