project:
  type: website
  output-dir: docs

website:
  title: "bmem-pc-4"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: page1.qmd
        text: Page 1
        
format:
  revealjs:
    theme: simple
    slide-number: true
    css: style.css
    chalkboard: true
    # embed-resources: true
    editor: visual

editor: visual

