project:
  type: website

website:
  title: "bmem-pc-4"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  revealjs:
    theme: simple
    slide-number: true
    css: style.css
    chalkboard: true
    # embed-resources: true
    editor: visual

editor: visual

